type: vertical-stack
cards:
  - color: rgb(51, 53, 58)
    color_type: label-card
    name: Focuser
    styles:
      card:
        - height: 20px
      name:
        - font-weight: bold
        - font-size: 14px
        - color: white
        - align-self: middle
        - padding-bottom: 4px
    type: custom:button-card
  - square: false
    columns: 2
    type: grid
    cards:
      - type: custom:mushroom-entity-card
        entity: sensor.pegasusastro_focuscube_2_position
        name: Position
        icon_type: none
        fill_container: true
      - align_state: center
        animate: false
        line_width: 2
        font_size: 20
        entities:
          - entity: sensor.pegasusastro_focuscube_2_position
            color: white
        hours_to_show: 2
        points_per_hour: 240
        show:
          name: false
          icon: false
          extrema: false
          labels: true
          state: false
        type: custom:mini-graph-card
